
name: TEST IN Ubuntu and in Macos

on:
  push:
    branches:
      - abouramd

jobs:
  test-macos:
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build and Test
        run: make all fclean
      
        
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build and Test
        run: make all fclean


