name: Merge abouramd branch into master

on:
  push:
    branches: [ "abouramd" ]

jobs:
  merge:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and Test
        run: make all fclean

      - name: Set name and email
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      
      - name: Checkout to master
          git checkout master
      
      - name: Merge with abouramd
          git merge --no-ff abouramd

      - name: Push to master
          git push origin master
